"""
Agentic Product Profile — ontology switch + generator priors.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any

PRESETS: dict[str, dict[str, Any]] = {
    "assistant_heavy": {
        "preset_id": "assistant_heavy",
        "label": "Personal assistant — inbox & calendar",
        "ontology_vertical": "agent_runtime",
        "ontology_version": "agent_runtime_v1",
        "billing_model": "b2b_subscription",
        "pricing_mode": "internal_budget",
        "default_model": "gpt-4o",
        "max_loops_threshold": 8,
        "cache_hit_rate": 0.7,
        "description": "Seats delegate email and calendar work. High approval volume; retention hinges on weekly habit, not one-off runs.",
        "priors": {
            "n_seats": 800,
            "n_capabilities": 12,
            "activation_rate": 0.62,
            "weekly_habit_rate": 0.48,
            "approval_fatigue_rate": 0.22,
            "trust_incident_rate": 0.04,
            "connector_error_rate": 0.08,
            "run_cost_per_success": 0.35,
            "seat_arpu_monthly": 49.99,
            "monthly_churn_base": 0.06,
            "revenue_per_1k_tokens": 0.02,
            "policy_cpso_cap": 0.50,
            "budget_cap_per_outcome_usd": 4.00,
            "human_baseline_usd": 18.40,
            "reviewer_loaded_hourly_usd": 85.0,
            "review_minutes_per_approval": 4.0,
        },
    },
    "workspace_crm": {
        "preset_id": "workspace_crm",
        "label": "CRM workspace — pipeline automations",
        "ontology_vertical": "capability_lifecycle",
        "ontology_version": "capability_lifecycle_v1",
        "billing_model": "b2b_subscription",
        "pricing_mode": "internal_budget",
        "default_model": "claude-3-5-sonnet",
        "max_loops_threshold": 10,
        "cache_hit_rate": 0.65,
        "description": "Overnight deal-pipeline agents wired to CRM tools. Connector depth and overnight-run reliability drive value.",
        "priors": {
            "n_seats": 1200,
            "n_capabilities": 18,
            "activation_rate": 0.55,
            "weekly_habit_rate": 0.52,
            "approval_fatigue_rate": 0.18,
            "trust_incident_rate": 0.03,
            "connector_error_rate": 0.12,
            "run_cost_per_success": 0.55,
            "seat_arpu_monthly": 79.0,
            "monthly_churn_base": 0.05,
            "revenue_per_1k_tokens": 0.025,
            "policy_cpso_cap": 0.50,
            "budget_cap_per_outcome_usd": 4.00,
            "human_baseline_usd": 18.40,
            "reviewer_loaded_hourly_usd": 85.0,
            "review_minutes_per_approval": 4.0,
        },
    },
    "ops_mission": {
        "preset_id": "ops_mission",
        "label": "Ops missions — docs & escalations",
        "ontology_vertical": "capability_lifecycle",
        "ontology_version": "capability_lifecycle_v1",
        "billing_model": "b2b_subscription",
        "pricing_mode": "internal_budget",
        "default_model": "gpt-4o",
        "max_loops_threshold": 12,
        "cache_hit_rate": 0.55,
        "description": "Multi-step back-office missions through document portals. Escalation-heavy; trust and approval friction are the risk.",
        "priors": {
            "n_seats": 400,
            "n_capabilities": 10,
            "activation_rate": 0.48,
            "weekly_habit_rate": 0.38,
            "approval_fatigue_rate": 0.28,
            "trust_incident_rate": 0.06,
            "connector_error_rate": 0.15,
            "run_cost_per_success": 0.85,
            "seat_arpu_monthly": 129.0,
            "monthly_churn_base": 0.07,
            "revenue_per_1k_tokens": 0.03,
            "policy_cpso_cap": 0.80,
            "budget_cap_per_outcome_usd": 6.00,
            "human_baseline_usd": 32.00,
            "reviewer_loaded_hourly_usd": 95.0,
            "review_minutes_per_approval": 6.0,
        },
    },
    "api_metered": {
        "preset_id": "api_metered",
        "label": "Metered agent API — usage-priced",
        "ontology_vertical": "agent_runtime",
        "ontology_version": "agent_runtime_v1",
        "billing_model": "usage_based",
        "pricing_mode": "product_sku",
        "default_model": "gpt-4o-mini",
        "max_loops_threshold": 8,
        "cache_hit_rate": 0.6,
        "description": "Usage-priced agent API where inference volume is revenue, not only COGS. Margins track successful outcomes per dollar of spend.",
        "priors": {
            "n_seats": 600,
            "n_capabilities": 10,
            "activation_rate": 0.58,
            "weekly_habit_rate": 0.5,
            "approval_fatigue_rate": 0.15,
            "trust_incident_rate": 0.035,
            "connector_error_rate": 0.09,
            "run_cost_per_success": 0.4,
            "seat_arpu_monthly": 0.0,
            "monthly_churn_base": 0.08,
            "revenue_per_1k_tokens": 0.04,
            "policy_cpso_cap": 0.50,
            "reviewer_loaded_hourly_usd": 85.0,
            "review_minutes_per_approval": 3.0,
        },
    },
    "marketplace_agentic": {
        "preset_id": "marketplace_agentic",
        "label": "Marketplace (agent-assisted GMV)",
        "ontology_vertical": "marketplace_commerce",
        "ontology_version": "marketplace_commerce_v1",
        "billing_model": "usage_based",
        "pricing_mode": "marketplace_take",
        "default_model": "gpt-4o",
        "max_loops_threshold": 10,
        "cache_hit_rate": 0.6,
        "description": "Two-sided marketplace with agent-assisted quotes, listings, and checkout. Platform take must cover inference cost.",
        "priors": {
            "n_seats": 500,
            "n_capabilities": 8,
            "activation_rate": 0.55,
            "weekly_habit_rate": 0.45,
            "approval_fatigue_rate": 0.18,
            "trust_incident_rate": 0.04,
            "connector_error_rate": 0.1,
            "run_cost_per_success": 0.55,
            "seat_arpu_monthly": 0.0,
            "monthly_churn_base": 0.06,
            "revenue_per_1k_tokens": 0.03,
            "agent_assist_share": 0.45,
            "take_rate": 0.12,
            "verification_rate": 0.75,
            "inference_cost_share_of_take": 0.35,
            "policy_cpso_cap": 0.20,
            "reviewer_loaded_hourly_usd": 75.0,
            "review_minutes_per_approval": 3.0,
        },
    },
    "openmed_v22": {
        "preset_id": "openmed_v22",
        "label": "OpenMed v2.2 — clinical SDK (case study)",
        "ontology_vertical": "clinical_runtime",
        "ontology_version": "clinical_runtime_v1",
        "case_study_id": "openmed_v2_2",
        "billing_model": "usage_based",
        "pricing_mode": "internal_budget",
        "default_model": "openmed-local",
        "max_loops_threshold": 10,
        "cache_hit_rate": 0.55,
        "description": (
            "Synthetic warehouse from OpenMed 2.2.0 public contracts — local de-id, grounding, "
            "FHIR/OMOP, Maple/Compass. Deployments are health-system tenants; review labor is COGS."
        ),
        "priors": {
            "n_seats": 120,
            "n_capabilities": 10,
            "activation_rate": 0.52,
            "weekly_habit_rate": 0.4,
            "approval_fatigue_rate": 0.32,
            "trust_incident_rate": 0.07,
            "connector_error_rate": 0.11,
            "run_cost_per_success": 0.62,
            "seat_arpu_monthly": 0.0,
            "monthly_churn_base": 0.04,
            "revenue_per_1k_tokens": 0.028,
            "clinical_review_rate": 0.94,
            "review_labor_usd_per_run": 3.1,
            "review_arrival_per_hr": 22.0,
            "review_service_per_hr": 5.5,
            "reviewer_count": 3,
            "clinical_harm_unit_usd": 9200.0,
            "policy_cpso_cap": 8.00,
            "budget_cap_per_outcome_usd": 8.00,
            "human_baseline_usd": 45.00,
            "reviewer_loaded_hourly_usd": 95.0,
            "review_minutes_per_approval": 12.0,
        },
    },
    "agentic_commerce": {
        "preset_id": "agentic_commerce",
        "label": "Agentic Commerce — autonomous negotiation & checkout",
        "ontology_vertical": "agentic_commerce",
        "ontology_version": "agentic_commerce_v1",
        "billing_model": "usage_based",
        "pricing_mode": "marketplace_take",
        "default_model": "gpt-4o",
        "max_loops_threshold": 6,
        "cache_hit_rate": 0.55,
        "description": (
            "Two-sided marketplace where AI agents negotiate, quote, and checkout autonomously. "
            "Platform take must cover inference cost plus negotiation labor overhead."
        ),
        "priors": {
            "n_seats": 400,
            "n_capabilities": 6,
            "activation_rate": 0.65,
            "weekly_habit_rate": 0.55,
            "approval_fatigue_rate": 0.10,
            "trust_incident_rate": 0.03,
            "connector_error_rate": 0.08,
            "run_cost_per_success": 0.45,
            "seat_arpu_monthly": 0.0,
            "monthly_churn_base": 0.05,
            "revenue_per_1k_tokens": 0.0,
            "take_rate": 0.10,
            "agent_assist_share": 0.70,
            "max_negotiation_discount": 0.15,
            "policy_cpso_cap": 0.15,
            "reviewer_loaded_hourly_usd": 75.0,
            "review_minutes_per_approval": 2.0,
        },
    },
    "frugal_router": {
        "preset_id": "frugal_router",
        "label": "Cost-Optimized Router — model cascade & caching",
        "ontology_vertical": "agent_runtime",
        "ontology_version": "agent_runtime_v1",
        "billing_model": "usage_based",
        "pricing_mode": "product_sku",
        "default_model": "flash_lite",
        "max_loops_threshold": 3,
        "cache_hit_rate": 0.80,
        "description": (
            "High-volume API product relying on RouteLLM-style model cascades and aggressive caching. "
            "Token cost management is the primary margin lever."
        ),
        "priors": {
            "n_seats": 2000,
            "n_capabilities": 8,
            "activation_rate": 0.70,
            "weekly_habit_rate": 0.60,
            "approval_fatigue_rate": 0.05,
            "trust_incident_rate": 0.02,
            "connector_error_rate": 0.05,
            "run_cost_per_success": 0.008,
            "seat_arpu_monthly": 0.0,
            "monthly_churn_base": 0.09,
            "revenue_per_1k_tokens": 0.01,
            "policy_cpso_cap": 0.02,
            "budget_cap_per_outcome_usd": 0.05,
            "human_baseline_usd": 0.0,
            "reviewer_loaded_hourly_usd": 0.0,
            "review_minutes_per_approval": 0.0,
        },
    },
}


def get_preset(preset_id: str) -> dict[str, Any]:
    if preset_id not in PRESETS:
        raise KeyError(f"Unknown preset: {preset_id}")
    return deepcopy(PRESETS[preset_id])


def list_presets() -> list[str]:
    return list(PRESETS.keys())
